config/routes.rb
Rails.application.routes.draw do
  resources :runs

end

app/models/run.rb
class Run < ActiveRecord::Base
  has_attached_file :gpx
  validates_attachment_content_type :gpx, content_type: ['application/xml']
  validates :gpx, attachment_presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: [:show, :edit, :update, :destroy]

  # GET /runs
  # GET /runs.json
  def index
    @runs = Run.all
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
  end

  # GET /runs/new
  def new
    @run = Run.new
  end

  # GET /runs/1/edit
  def edit
  end

  # POST /runs
  # POST /runs.json
  def create
    @run = Run.new(run_params)

    respond_to do |format|
      if @run.save
        format.html { redirect_to @run, notice: 'Run was successfully created.' }
        format.json { render :show, status: :created, location: @run }
      else
        format.html { render :new }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
  def update
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to @run, notice: 'Run was successfully updated.' }
        format.json { render :show, status: :ok, location: @run }
      else
        format.html { render :edit }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to runs_url, notice: 'Run was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      params.fetch(:run, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render partial: 'layouts/shared/head' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/shared/_head.html.erb
<title>Track</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<%= yield :head %>

app/views/runs/_form.html.erb
<%= simple_form_for @run do |form| %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.input :gpx, as: :file %>
  <%= form.button :submit %>
<% end %>

app/views/runs/edit.html.erb
<h1>Editing Run</h1>

<%= render 'form' %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', runs_path %>

app/views/runs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Runs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @runs.each do |run| %>
      <tr>
        <td><%= link_to run.start_at, run %></td>
        <td><%= link_to 'Edit', edit_run_path(run) %></td>
        <td><%= link_to 'Destroy', run, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Run', new_run_path %>

app/views/runs/new.html.erb
<h1>New Run</h1>

<%= render 'form' %>

<%= link_to 'Back', runs_path %>

app/views/runs/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'map'%>
<% end %>
<p id="notice"><%= notice %></p>
<h1>Basic OSM Example</h1>

<div id="map" style="width: 100%; height: 400px;"
     data-lat="<%= @run.lat %>"
     data-lon="<%= @run.lon %>"
     data-gpx="<%= @run.gpx.url %>">
</div>

<%= t('distance') %> <%= @run.distance%>
<%= t('duration') %> <%= @run.duration%>
<%= t('start_at') %> <%= @run.start_at%>
<%= t('average_speed') %> <%= @run.average_speed%>
<%= t('lowest') %> <%= @run.lowest%>
<%= t('highest') %> <%= @run.highest%>
<%= link_to 'Edit', edit_run_path(@run) %> |
<%= link_to 'Back', runs_path %>